export const SET_TAB = "SET_TAB";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_QTYTYPE = "UPDATE_QTYTYPE";
export const TOOGLE_LOADING = "TOOGLE_LOADING";