export const CHANGE_TAB = "CHANGE_TAB";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_SUPPLIER = "GET_SUPPLIER";
export const GET_CUSTOMER = "GET_CUSTOMER";
export const GET_BRAND = "GET_BRAND";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_QTYTYPE = "GET_QTYTYPE";
export const GET_COLOR = "GET_COLOR";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const UPDATE_QTYTYPE = "UPDATE_QTYTYPE";
export const TOOGLE_LOADING = "TOOGLE_LOADING";